apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-prod
  name: demo-prod
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-0.0.1
  type: LoadBalancer